version: '3'
services:
  mysql_gpt:
    build:
      context: ./
      dockerfile: Dockerfile_mysql
    container_name: mysql_gpt
    # 这里暴露给宿主机方便调试
    ports:
      - 3309:3306
    #    environment:
    #      MYSQL_ROOT_PASSWORD: 123456 #设置root帐号密码
    volumes:
      - ~/mydata/mysql/data:/var/lib/mysql #数据文件挂载
      - ~/mydata/mysql/conf:/etc/mysql/conf.d #配置文件挂载
      - ~/mydata/mysql/log:/var/log/mysql #日志文件挂载
    networks:
      my-network:
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping" , "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5

  java_chatgpt:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: java_chatgpt
    environment:
      - PARAMS=--spring.datasource.url=jdbc:mysql://mysql_gpt:3306/chat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai \
        --spring.datasource.username=root \
        --spring.datasource.password=123456 \
        --chat.openai_api_key=xxxxx
        --chat.http_proxy_host= \
        --chat.http_proxy_port= \
      - SPRING_PROFILES_ACTIVE=dev
      # 这里要用mysql_gpt的3306端口
      - JDBC_URL=jdbc:mysql://mysql_gpt:3306/chat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - MYSQL_USER_NAME=root
      - MYSQL_PASSWORD=123456
      - CHAT_OPENAI_API_KEY=xxx
      - CHAT_OPENAI_ACCESS_TOKEN=
      - CHAT_OPENAI_API_BASE_URL=https://api.openai.com/
      - CHAT_HTTP_PROXY_HOST:127.0.0.1
      - CHAT_HTTP_PROXY_PORT:33210
    ports:
      - 3002:3002
    depends_on:
      - mysql_gpt
    restart: on-failure
    networks:
      my-network:

networks:
  my-network:

